# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpage_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
    ]
