# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_blogpage_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='source',
        ),
    ]
