# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blogpage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
