# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 01:32
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blogpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
