# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_archivepage_mediapage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'blog reeksen',
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reeks',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.BlogReeks'),
        ),
    ]
