# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0020_auto_20170525_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_items', to='core.BlogPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_blogpagecategory_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
